[project]
name = "use-pymilvus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jieba>=0.42.1",
    "langchain-text-splitters>=1.0.0",
    "pymilvus>=2.6.4",
]
